SELECT ROW_NUMBER() over(Order by DTIn) AS NO,* FROM(
SELECT 
CASE
WHEN CAST(DTIn AS TIME) > CAST(@para2 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para3 AS TIME) THEN CAST(DTIn as date)
WHEN CAST(DTIn AS TIME) > CAST(@para4 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para5 AS TIME) THEN CAST(DATEADD(DAY,-1, DTIn) as date)
ELSE '1999-01-01'
END as RANGE,
FL, DTIn, DTOut, Reason
FROM TblInOut
WHERE Stat = @para6) AS l
WHERE RANGE = @para1
#
SELECT ROW_NUMBER() over(Order by RANGE) AS NO,* FROM(
SELECT 
CASE
WHEN CAST(DTIn AS TIME) > CAST(@para8 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para9 AS TIME) THEN CAST(DTIn as date)
WHEN CAST(DTIn AS TIME) > CAST(@para10 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para11 AS TIME) THEN CAST(DATEADD(DAY,-1, DTIn) as date)
ELSE '1999-01-01'
END as RANGE,
FL, DTIn, DTOut, Reason
FROM TblInOut
WHERE Stat = @para12) AS l
WHERE RANGE = @para7
#
SELECT ROW_NUMBER() over(Order by RANGE) AS NO,* FROM(
SELECT 
CASE
WHEN CAST(DTIn AS TIME) > CAST(@para14 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para15 AS TIME) THEN CAST(DTIn as date)
WHEN CAST(DTIn AS TIME) > CAST(@para16 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para17 AS TIME) THEN CAST(DATEADD(DAY,-1, DTIn) as date)
ELSE '1999-01-01'
END as RANGE,
FL, DTIn, DTOut, Reason
FROM TblInOut
WHERE Stat = @para18) AS l
WHERE RANGE = @para13
#
SELECT ROW_NUMBER() over(Order by RANGE) AS NO,* FROM(
SELECT 
CASE
WHEN CAST(DTIn AS TIME) > CAST(@para20 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para21 AS TIME) THEN CAST(DTIn as date)
WHEN CAST(DTIn AS TIME) > CAST(@para22 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para23 AS TIME) THEN CAST(DATEADD(DAY,-1, DTIn) as date)
ELSE '1999-01-01'
END as RANGE,
FL, DTIn, DTOut, Reason
FROM TblInOut
WHERE Stat = '22' OR Stat ='33' OR Stat ='44' OR Stat ='55' OR Stat ='66' OR Stat ='77' OR Stat ='88' OR Stat ='99') AS l
WHERE RANGE = @para19
#
SELECT ROW_NUMBER() over(Order by RANGE) AS NO,* FROM(
SELECT 
CASE
WHEN CAST(DTIn AS TIME) > CAST(@para26 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para27 AS TIME) THEN CAST(DTIn as date)
WHEN CAST(DTIn AS TIME) > CAST(@para28 AS TIME) AND CAST(DTIn AS TIME) < CAST(@para29 AS TIME) THEN CAST(DATEADD(DAY,-1, DTIn) as date)
ELSE '1999-01-01'
END as RANGE,
FL, DTIn, DTOut, Reason
FROM TblInOut
WHERE Stat = @para30) AS l
WHERE RANGE = @para25
